name: Symfony CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker containers
        run: docker compose build

      - name: Install Dependencies
        run: docker compose run --rm app composer install --no-interaction

  code_quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker containers
        run: docker compose build

      - name: Install Dependencies
        run: docker compose run --rm app composer install --no-interaction

      - name: Run PHP CS Fixer
        run: docker compose run --rm app composer phpcsfixer

  phpstan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker containers
        run: docker-compose build

      - name: Install Dependencies
        run: docker-compose run --rm app composer install --no-interaction

      - name: Run PHPStan
        run: docker-compose run --rm app composer phpstan


  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker containers
        run: docker compose build

      - name: Install Dependencies
        run: docker compose run --rm app composer install --no-interaction

      - name: Setup Database
        run: |
          docker compose run --rm app php bin/console doctrine:database:drop --if-exists --force --env=dev
          docker compose run --rm app php bin/console doctrine:database:create --env=dev
          docker compose run --rm app php bin/console doctrine:migrations:migrate --no-interaction --env=dev

      - name: Run PHPUnit tests
        run: docker compose run --rm app php vendor/bin/phpunit

  parse_command:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker containers
        run: docker compose build

      - name: Install Dependencies
        run: docker compose run --rm app composer install --no-interaction

      - name: Setup Database
        run: |
          docker compose run --rm app php bin/console doctrine:database:drop --if-exists --force --env=dev
          docker compose run --rm app php bin/console doctrine:database:create --env=dev
          docker compose run --rm app php bin/console doctrine:migrations:migrate --no-interaction --env=dev

      - name: Run Parse Command
        run: docker compose run --rm app php bin/console app:parse --env=test